version: '3'
services:
  rss:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./database:/database
    environment:
      TRAEWELLING_CLIENT_ID: 14
      TRAEWELLING_CLIENT_SECRET: kOEymkuc1TKgFMch7W8PD51Lag9WJNhnwIH2bhEG
      PUBLIC_URL: http://localhost